version: "3.8"

services:
  db:
    image: mysql:5.7
    container_name: "db_service_api"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "somepassword"
      MYSQL_DATABASE: "ticketsDb"
    networks:
      - fullstack
    ports:
      - "6033:3306"
    volumes:
      - dbdata:/var/lib/mysql

  web:
    build: .
    container_name: "rest-api"
    environment:
      MYSQL_ROOT_PASSWORD: "somepassword"
      MYSQL_DATABASE: "ticketsDb"
      MYSQL_HOST: "db"
      MYSQL_PORT: "3306"
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - fullstack
volumes:
  dbdata:

networks:
  fullstack:
    driver: bridge